name: Publish NuGet Package 223

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the action
  
jobs:
  build:
    runs-on: ubuntu-latest     

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Change to the .NET version you are using

       - name: Install GitVersion
        run: dotnet tool install -g GitVersion.Tool

      - name: Determine version
        id: gitversion
        run: gitversion /output json /output buildserver
        env:
          GITHUB_TOKEN: ${{ secrets.GT_KEY }}

      - name: Set up GitVersion variables
        run: echo "##vso[task.setvariable variable=PackageVersion]${{ steps.gitversion.outputs.SemVer }}"
        

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkgs

    - name: Publish NuGet package     
      run: dotnet nuget push /home/runner/work/NuGetPackage/NuGetPackage/nupkgs/*.nupkg --api-key ${{ secrets.GT_KEY }}  --source "github"
