name: Publish NuGet Package 132

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the action
  
jobs:
  build:
    runs-on: ubuntu-latest     

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'  # Change to the .NET version you are using

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkgs

    - name: Publish NuGet package     
      run: dotnet nuget push "/home/runner/work/NuGetPackage/NuGetPackage/nupkgs/AppLogger.1.0.0.nupkg" --api-key "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" --source "https://nuget.pkg.github.com/idhasitha/index.json"
